apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name}}
  namespace: {{ .Release.Namespace}}
spec:
  selector:
{{ include "selector.labels" . | indent 4}}
  ports:
    - protocol: TCP
      port: 8090          # expose or external or service port
      targetPort: 8090  #container port